$DnsServers = "VDVMADDC01.SVC.PROD.VEGAS.COM","VVVMADDC02.SVC.PROD.VEGAS.COM","VDRMADDC01.RES.VEGAS.COM","VVRMADDC02.RES.VEGAS.COM","VDCMADDC01.CORP.VEGAS.COM","VVCMADDC02.CORP.VEGAS.COM" # "VVOMADDC01.PROD.VEGAS.COM","VVOMADDC02.PROD.VEGAS.COM"
$lookup = "tableau.vegas.com"
ForEach ($srv in $DnsServers){
    Resolve-DnsName -Server $srv -Name $lookup }